[tool.poetry]
name = "snomed-rag"
version = "0.1.0"
description = ""
authors = ["jenniferjiangkells <jenniferjiangkells@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
langchain = ">=0.2,<0.3"
langchain-community = ">=0.2,<0.3"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.22"

[tool.langserve]
export_module = "snomed_rag"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
